// <auto-generated />
using System;
using Auth_Service.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Auth_Service.Migrations
{
    [DbContext(typeof(AuthContext))]
    [Migration("20200913002846_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Auth_Service.Domain.Models.TblUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Firstname")
                        .HasColumnName("Firstname")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Lastname")
                        .HasColumnName("Lastname")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Password")
                        .HasColumnName("password")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200)
                        .IsUnicode(true);

                    b.Property<DateTime>("RegistrationTimeStamp")
                        .HasColumnName("RegistrationTimeStamp")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Status")
                        .HasColumnType("TEXT")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasDefaultValue("Active");

                    b.Property<decimal>("WalletBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("WalletBalance")
                        .HasColumnType("money")
                        .HasDefaultValue(0m);

                    b.HasKey("UserId");

                    b.ToTable("TblUser");

                    b.HasData(
                        new
                        {
                            UserId = 1000L,
                            Email = "test@gmail.com",
                            Firstname = "Temitope",
                            Lastname = "Oniyide",
                            Password = "2gDuvyv7z/ZRGZ9swC3KjA==",
                            RegistrationTimeStamp = new DateTime(2020, 9, 13, 1, 28, 45, 610, DateTimeKind.Local).AddTicks(1401),
                            WalletBalance = 0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
